CREATE DATABASE IF NOT EXISTS baas;

USE baas;

-- Payment API Client Subscriber

DROP TABLE IF EXISTS NOTIFICATIONS;

CREATE TABLE IF NOT EXISTS  NOTIFICATIONS (
	CLIENT VARCHAR(50)  not null,
    TYPE VARCHAR(50)  not null,
    STATUS VARCHAR(50) not null,
    COUNT BIGINT(5) default 1,
    PRIMARY KEY (CLIENT,TYPE,STATUS)
);


INSERT INTO NOTIFICATIONS(CLIENT,TYPE,STATUS) VALUES('SQL','Payment','Received');
INSERT INTO NOTIFICATIONS(CLIENT,TYPE,STATUS) VALUES('SQL','Payment','Processing');
INSERT INTO NOTIFICATIONS(CLIENT,TYPE,STATUS) VALUES('SQL','Payment','Scheduled');

INSERT INTO NOTIFICATIONS(CLIENT,TYPE,STATUS) VALUES('SQL','Location','Received');
INSERT INTO NOTIFICATIONS(CLIENT,TYPE,STATUS) VALUES('SQL','Location','Processing');
INSERT INTO NOTIFICATIONS(CLIENT,TYPE,STATUS) VALUES('SQL','Location','Scheduled');


INSERT INTO NOTIFICATIONS(CLIENT,TYPE,STATUS) VALUES('SQL','Foreign Exchange','Received');
INSERT INTO NOTIFICATIONS(CLIENT,TYPE,STATUS) VALUES('SQL','Foreign Exchange','Processing');
INSERT INTO NOTIFICATIONS(CLIENT,TYPE,STATUS) VALUES('SQL','Foreign Exchange','Scheduled');


UPDATE NOTIFICATIONS SET COUNT =  COUNT  + 1 WHERE CLIENT=  'SQL' AND TYPE=  'Foreign Exchange' AND STATUS=  'Received';
UPDATE NOTIFICATIONS SET COUNT =  COUNT  + 1 WHERE CLIENT=  'SQL' AND TYPE=  'Foreign Exchange' AND STATUS=  'Received';
UPDATE NOTIFICATIONS SET COUNT =  COUNT  + 1 WHERE CLIENT=  'SQL' AND TYPE=  'Foreign Exchange' AND STATUS=  'Received';

SELECT 
    CLIENT,TYPE, STATUS, COUNT
FROM
    NOTIFICATIONS;
